import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SearchBar from './components/SearchBar';
import Image from 'next/image';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <header className="fixed top-0 left-0 z-50 p-4 flex items-center space-x-4 bg-white shadow-sm">
          <Image
            src="/BRACU DIARY.svg"
            alt="BRACU Diary Logo"
            width={120}
            height={100}
            className="object-contain"
          />
          <Image
            src="/logo.svg"
            alt="BRACU Diary Logo"
            width={40}
            height={40}
            className="object-contain"
          />
          <SearchBar />
        </header>
        <main className="flex-grow pt-16">{children}</main>
      </body>
    </html>
  );
}